name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          aws ecr get-login-password --region {ECR-AWS-ZONE} | docker login --username AWS --password-stdin {AWS-ACCOUNT-ID}.dkr.ecr.{ECR-AWS-ZONE}.amazonaws.com/{ECR-REPO-NAME}
          docker build -t my-lambda-image-test -f Dockerfile .
          docker tag my-lambda-image-test:latest {AWS-ACCOUNT-ID}.dkr.ecr.{ECR-AWS-ZONE}.amazonaws.com/{ECR-REPO-NAME}:latest
          docker push {AWS-ACCOUNT-ID}.dkr.ecr.{ECR-AWS-ZONE}.amazonaws.com/{ECR-REPO-NAME}:latest
      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name {LAMBDA-FUNCTION-NAME} --image-uri {AWS-ACCOUNT-ID}.dkr.ecr.{ECR-AWS-ZONE}.amazonaws.com/{ECR-REPO-NAME}:latest
       
